# ============================================================
# RTAB-Map Handheld Mapping Config (ORB-only, no base_link)
# For Realsense D435i, ROS2 Humble, Jetson
# ============================================================

rtabmap:
  ros__parameters:

    # --- Frame / Odometry ---
    frame_id: "camera_link"           # Camera frame as root
    odom_frame_id: ""                 # No robot base / odom frame
    subscribe_odom_info: false        # No external odometry
    approx_sync: false                # Approximate time sync for RGB-D + IMU
    wait_imu_to_init: true
    wait_for_transform_duration: 1.0
    map_frame_id: "map"

    # --- Visual Features (ORB only) ---
    Vis/FeatureType: "6"              # ORB features
    Kp/DetectorStrategy: "6"          # ORB detector
    Vis/MaxFeatures: "800"
    Vis/MinInliers: "20"
    Vis/Iterations: "600"

    # --- Odometry ---
    Odometry/Strategy: "0"            # RGB-D visual odometry
    Odometry/MaxFeatures: "1000"
    Odometry/MinInliers: "10"
    Odom/GuessMotion: true
    Odometry/LinearUpdate: "0.08"
    Odometry/AngularUpdate: "0.06"
    Odometry/LocalRadius: "30"
    Odometry/OptimizeMaxError: "1.5"

    # --- RGB-D Keyframe / Node ---
    RGBD/Enabled: true
    RGBD/ImagesAlreadyRectified: true
    RGBD/LinearUpdate: "0.02"
    RGBD/AngularUpdate: "0.02"
    RGBD/LocalRadius: "30"
    RGBD/NeighborLinkRefining: true
    RGBD/ProximityBySpace: true
    RGBD/ProximityAngle: 120
    RGBD/ProximityMaxGraphDepth: 150
    RGBD/ProximityMaxPaths: 7
    RGBD/CreateOccupancyGrid: true
    RGBD/OptimizeMaxError: 1.5

    # --- Loop Closure / Graph Optimization ---
    Rtabmap/DetectionRate: 3.0
    Rtabmap/LoopThr: 0.2
    Optimizer/Strategy: 2
    Optimizer/Iterations: 60
    g2o/PixelVariance: 0.3

    # --- Occupancy Grid ---
    Grid/RangeMax: 4.0
    Grid/CellSize: 0.05
    Grid/MaxObstacleHeight: 3.0
    Grid/MinClusterSize: 30
    Grid/NormalsSegmentation: true
    Grid/FlatObstacleDetected: true
    Grid/GroundIsObstacle: false
    Grid/NoiseFilteringRadius: 0.15
    Grid/NoiseFilteringMinNeighbors: 15

    # --- Memory ---
    Mem/STMSize: 30
    Mem/RecentWmRatio: 0.4
    Mem/IncrementalMemory: true
    Rtabmap/TimeThr: 1000
